import{a as S,S as w,i}from"./assets/vendor-KnZd4sWe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const L="48994521-1332b5dc6d32291391eccb048",E="https://pixabay.com/api/";async function y(r,t){const s=new URLSearchParams({q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:40}),a=`${E}?key=${L}&${s.toString()}`;try{const e=await S.get(a);return e.data.hits.length===0?Promise.reject(new Error("No images found.")):{images:e.data.hits,totalHits:e.data.totalHits}}catch{throw new Error("Failed to fetch images.")}}const f=document.querySelector(".gallery");let q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:n,comments:h,downloads:b})=>`
      <a href="${a}" class="gallery-item">
        <img src="${s}" alt="${e}" />
        <div class="info">
          <p>Likes ${o}</p>
          <p>Views ${n}</p>
          <p>Comments ${h}</p>
          <p>Downloads ${b}</p>
        </div>
      </a>
      `).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function $(){f.innerHTML=""}const m=document.querySelector("#search-form"),d=document.querySelector(".loader");document.querySelector(".gallery");const u=document.querySelector(".load-more");let c="",l=1;const p=40;m.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!c){i.error({title:"Error",message:"Please enter a search query!"});return}$(),l=1,d.style.display="block",u.style.display="none";try{const{images:t,totalHits:s}=await y(c,l);t.length>0?(g(t),i.success({title:"Success",message:"Images loaded!"}),s>p&&(u.style.display="block")):i.error({title:"Error",message:"No images found."})}catch(t){i.error({title:"Error",message:t.message})}finally{d.style.display="none",m.reset()}});u.addEventListener("click",async()=>{l+=1,d.style.display="block";try{const{images:r,totalHits:t}=await y(c,l);r.length>0&&(g(r),v(),t<=l*p&&(u.style.display="none",i.error({title:"Error",message:"We're sorry, but you've reached the end of search results."})))}catch(r){i.error({title:"Error",message:r.message})}finally{d.style.display="none"}});function v(){const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
